[package]
name = "rust_sqlserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tiberius = { version="0.12.3" ,features = ["sql-browser-tokio"]}
tokio = { version = "1.45.0",features = ["net", "macros", "rt-multi-thread"] }
tokio-util = {version = "0.7.15",features = ["compat"]}
